version: '3.8'

services:
  app:
    build: .
    ports:
      - "3009:3009"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - JWT_SECRET=${JWT_SECRET} 
  db:
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5433
    volumes:
      - ./docker-data/db:/lib/postgresql/data
