version: '3.8'

services:
  app:
    build: .
    ports:
      - "3010:3010"
    environment:
      DATABASE_URL: postgresql://postgres:shazam@localhost:5435/picapau?schema=public
    depends_on:
      - db
    command: sh -c "npx prisma migrate deploy && npm run start"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shazam
      POSTGRES_DB: picapau
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
